spring.application.name=parking-control
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# definindo para que sempre que a gente crie/mapeie entidades, colunas; Na hora que executar a aplicação criar automaticamente na base de dados
spring.jpa.hibernate.ddl-auto=update

# o hibernate procura metadados quando inicia a aplicação, essa config é para evitar alguns erros comuns e conflitos
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
